name: On-Demand Connector Builder

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - ready_for_review
      - reopened
  workflow_dispatch:
    inputs:
      comment-id:
        description: "Optional comment-id of the slash command. Ignore if not applicable."
        required: false
      pr:
        description: "PR Number"
        required: false

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  run-connector-build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      # matrix: ${{ fromJson(needs.get-connector-jobs.outputs.jobs) }}
      matrix:
        include:
        - api_name: "JSONPlaceholder"
        - api_name: "PokemonTGG"
        - api_name: "Hubspot"
          connector_name: "source-hubspot"
          config_name: "config"
    name: Build ${{ matrix.api_name }} Connector
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    steps:

      # Some MCP Servers need npx/node, so set that up:
      - name: Set up Node.js and npx
        uses: actions/setup-node@v5.0.0
        with:
          node-version: '20'

      - name: Checkout `connector-builder-mcp` repo
        uses: actions/checkout@v5
        with:
          fetch-depth: 1

      - name: Run Poe Slash Command Processor
        uses: aaronsteers/poe-command-processor@v1
        env:
          GCP_GSM_CREDENTIALS: ${{ secrets.GCP_GSM_CREDENTIALS }}
        with:
          pr: ${{ github.event.inputs.pr }}
          comment-id: ${{ github.event.inputs.comment-id }}
          start-message: "ðŸ› ï¸ Building connector..."
          github-token: ${{ secrets.GITHUB_TOKEN }}
          command: >
            build-connector
            --api-name='${{ matrix.api_name }}'
            ${{ matrix.connector_name && format('--existing-connector-name={0}', matrix.connector_name) || '' }}
            ${{ matrix.config_name && format('--existing-config-name={0}', matrix.config_name) || '' }}
          no-commit: true
